<section id="presentacion" aria-labelledby="presentacion-title" class="section section--presentacion">
  <div class="container">

    <p>La Comisión Corográfica de la Nueva Granada (1850–1859), dirigida por Agustín Codazzi, fue un hito para las ciencias y la historia territorial de Colombia. Produjo mapas, descripciones de paisajes, economías y poblaciones, e inventarios de caminos y recursos que documentan la diversidad geográfica, natural y cultural del país. Ese acervo —informes, crónicas, láminas y documentación manuscrita e impresa— se conserva hoy disperso en bibliotecas, archivos, museos y colecciones públicas y privadas dentro y fuera de Colombia. En años recientes, miles de documentos de la Comisión resguardados en la Biblioteca Nacional Universitaria de Turín —entre ellos decenas de mapas manuscritos originales de Codazzi— fueron digitalizados en alta resolución; una copia se entregó al Archivo General de la Nación. A partir de este corpus se realizó la exposición <strong>“Codazzi: cartografía de un archivo global”</strong>, que reavivó el interés académico por la Comisión y su legado.</p>

    <p>La <strong>Comisión Corográfica Digital (CCD)</strong> surge como una alianza de especialistas e instituciones para <em>enlazar, describir y publicar</em> este patrimonio con herramientas de las humanidades digitales (datos enlazados, repositorio, curadurías e información geoespacial).</p> 
    
    <p>Participan como custodios activos el Archivo General de la Nación (AGN), el Banco de la República (BANREP), la Biblioteca Nacional de Colombia (BNC), la Biblioteca Nacional Universitaria de Turín (BNUTo), el Instituto Geográfico Agustín Codazzi (IGAC), el Museo Nacional de Colombia (MNC), la Sociedad Colombiana de Ingenieros (SCI), la Sociedad Geográfica de Colombia (SOGEOCOL), la Sociedad de Mejoras y Ornato de Bogotá (SMOB) y la Universidad Nacional de Colombia (UN) —incluyendo el Archivo Central e Histórico de la Universidad Nacional de Colombia y el Instituto de Ciencias Naturales—, entre otros. Apoyan además la Fundación Neogranadina (FN), el Instituto Italiano de Cultura (IIC), el Laboratorio de Cartografía Histórica e Historia Digital del Departamento de Historia de la Universidad Nacional (CaHID), la Red Colombiana de Humanidades Digitales (RCHD) y Razón Cartográfica – Red de Historias de las Geografías y Cartografías de Colombia (RC).</p>
    
    <p>El Comité Científico lo integran Nancy Appelbaum, Sebastián Díaz Ángel, Lucía Duque Muñoz, Stefania Gallini, David Ramírez Palacios, Juanita Rodríguez Congote, Efraín Sánchez Cabra y Juan Felipe Urueña Calderón.</p>
  </div>
</section>
